# Generated by Django 5.2.7 on 2025-10-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('menor_edad', models.BooleanField()),
                ('IBAN', models.CharField(blank=True, max_length=34, null=True)),
            ],
        ),
    ]
