# Generated by Django 5.2.7 on 2025-10-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direccion",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("calle", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=10)),
                ("piso", models.CharField(blank=True, max_length=10, null=True)),
                ("otros", models.CharField(blank=True, max_length=50, null=True)),
                ("ciudad", models.CharField(max_length=100)),
                ("codigo_postal", models.DecimalField(decimal_places=0, max_digits=5)),
                ("pais", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="socio",
            name="documento_identidad",
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="socio",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
