# Generated by Django 5.2.7 on 2025-11-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_direccion_socio_documento_identidad_alter_socio_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='direccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='socios.direccion'),
        ),
        migrations.AddField(
            model_name='socio',
            name='domicilia_pago',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='role',
            field=models.CharField(choices=[('ROOT', 'Superusuario'), ('ADMIN', 'Directivo'), ('USER', 'Usuario')], default='USER', max_length=5),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=models.CharField(default='España', max_length=100),
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=200)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('documento_identidad', models.CharField(max_length=9, null=True, unique=True)),
                ('direccion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_legal', to='socios.direccion')),
            ],
        ),
        migrations.AddField(
            model_name='socio',
            name='tutor_legal',
            field=models.ManyToManyField(blank=True, null=True, related_name='socios', to='socios.tutor'),
        ),
    ]
